#!/usr/bin/env node

const fs = require("fs");
const MongoClient = require("mongodb").MongoClient;

let cachedClient = null;
let cachedDb = null;

async function connectToDatabase(uri) {
  if (cachedDb) return cachedDb;

  const client = new MongoClient(uri, {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  });
  await client.connect();
  const db = await client.db(new URL(uri).pathname.slice(1));

  cachedClient = client;
  cachedDb = db;
  return db;
}

async function insertFileToDB(jsonFile, collection) {
  const contents = fs.readFileSync(jsonFile, "utf8");
  const data = JSON.parse(contents);
  const chars = [];
  for (const c in data) {
    // String.fromCodePoint(22909) // => "好"
    const s = String.fromCodePoint(Number(c));
    data[c].char = s;
    chars.push(data[c]);
  }
  await collection.createIndex(
    { char: 1 },
    {
      name: "按字符本身检索"
    }
  );
  await collection.insertMany(chars);
}

async function main() {
  const MONGODB_URI = process.env.MONGODB_URI || `mongodb://localhost:27017/unihan`;
  const db = await connectToDatabase(MONGODB_URI);
  const collection = await db.collection("chars");
  await insertFileToDB("unihan.json", collection);
  cachedClient.close();
}

main();
