name: 检查 Unicode 最新版本

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      name: Check latest Unicode Version
      run: |
        curl -I https://www.unicode.org/versions/latest/ | grep 13.0.0
